[package]
name = "wiki_game_solver_web"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2"
tokio = { version = "1", features = ["full"] }
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fs2 = "0"